development:
  bucket: myappdevelopment
  access_key_id:  141FZ8BYA4AK5PBXBWR2
  secret_access_key:  0X0JaZqtAILLvUCduD4StoyxEQOIUgV1Lbm5qjHN

test:
  bucket: myapptest
  access_key_id:  141FZ8BYA4AK5PBXBWR2
  secret_access_key:  0X0JaZqtAILLvUCduD4StoyxEQOIUgV1Lbm5qjHN

production:
  bucket: myapp
  access_key_id:  141FZ8BYA4AK5PBXBWR2
  secret_access_key:  0X0JaZqtAILLvUCduD4StoyxEQOIUgV1Lbm5qjHN